---
output:
  pdf_document: default
  html_document: default
---
Q1
```{r}
### a)
# We can use T.test or ANOVA to see the difference.
```


```{r}
### b)
library('BSDA')

CS_Mean<- c(0.04, 0.22, 0.43, 0.76)
CS_sd <- c(0.11, 0.17, 0.35, 0.58)
CS_n <- c(27, 9, 7, 10)

tsum.test (CS_Mean[1], s.x=CS_sd[1], n.x=CS_n[1], CS_Mean[2], s.y=CS_sd[2], n.y=CS_n[2])

tsum.test (CS_Mean[2], s.x=CS_sd[2], n.x=CS_n[2], CS_Mean[3], s.y=CS_sd[3], n.y=CS_n[3])

# p-value can be get from above by compare two different group. The first is between group1 (normal unchanged) 
# and group 2 (normal Questionably or mildly affected). two tailed p-value is 0.01346.

```


Q2
```{r}
### a)

HORMONE_DB <-read.csv('D:/R632/HW2/HORMONECSV.csv')

class(HORMONE_DB$Hormone) = "character"

biliary_secretion_change<- (HORMONE_DB$Bilsecpr-HORMONE_DB$Bilsecpt)
Hormone_group <- HORMONE_DB$Hormone
model <- aov(biliary_secretion_change ~ Hormone_group)

summary(model)
TukeyHSD(model)

#group 4 and 3 is specific differences
```

```{r}
### b)

pancreatic_secretion_change<- (HORMONE_DB$Pansecpr-HORMONE_DB$Pansecpt)

model <- aov(pancreatic_secretion_change ~ Hormone_group)

summary(model)
TukeyHSD(model)

#group 5 and 2 is specific differences
```

```{r}
### c)

biliary_pH_change<- (HORMONE_DB$Bilphpr-HORMONE_DB$Bilphpt)

model <- aov(biliary_pH_change ~ Hormone_group)

summary(model)
TukeyHSD(model)

#group 3 and 2 is specific differences
```
```{r}
### d)

pancreatic_pH_change<- (HORMONE_DB$Panphpr-HORMONE_DB$Panphpt)

model <- aov(pancreatic_pH_change ~ Hormone_group)

summary(model)
TukeyHSD(model)

#group 5 and 2 is specific differences
```


Q3
```{r}
### a) day 7 vs day 0

CORNEAL_DB <-read.csv('D:/R632/HW2/CORNEALCSV.csv')

class(CORNEAL_DB$tr) = "character"
Drug_group <- CORNEAL_DB$tr

# changes from day 0 tp day 7
c_0_7<- (CORNEAL_DB$c1-CORNEAL_DB$c2)
s_0_7<- (CORNEAL_DB$s1-CORNEAL_DB$s2)
i_0_7<- (CORNEAL_DB$i1-CORNEAL_DB$i2)
t_0_7<- (CORNEAL_DB$t1-CORNEAL_DB$t2)
n_0_7<- (CORNEAL_DB$n1-CORNEAL_DB$n2)

cat ('Central day 7 vs day 0')
model <- aov(c_0_7 ~ Drug_group)
TukeyHSD(model)
confint(model, level=0.95)

cat ('\n','Superior day 7 vs day 0')
model <- aov(s_0_7 ~ Drug_group)
TukeyHSD(model)
confint(model, level=0.95)

cat ('\n','Inferior day 7 vs day 0')
model <- aov(i_0_7 ~ Drug_group)
TukeyHSD(model)
confint(model, level=0.95)

cat ('\n','Temporal day 7 vs day 0')
model <- aov(t_0_7 ~ Drug_group)
TukeyHSD(model)
confint(model, level=0.95)

cat ('\n','Nasal day 7 vs day 0')
model <- aov(n_0_7 ~ Drug_group)
TukeyHSD(model)
confint(model, level=0.95)
```
```{r}
### a) day 14 vs day 0

# changes from day 0 tp day 7
c_0_14<- (CORNEAL_DB$c1-CORNEAL_DB$c3)
s_0_14<- (CORNEAL_DB$s1-CORNEAL_DB$s3)
i_0_14<- (CORNEAL_DB$i1-CORNEAL_DB$i3)
t_0_14<- (CORNEAL_DB$t1-CORNEAL_DB$t3)
n_0_14<- (CORNEAL_DB$n1-CORNEAL_DB$n3)

cat ('Central day 14 vs day 0')
model <- aov(c_0_14 ~ Drug_group)
TukeyHSD(model)
confint(model, level=0.95)

cat ('\n','Superior day 14 vs day 0')
model <- aov(s_0_14 ~ Drug_group)
TukeyHSD(model)
confint(model, level=0.95)

cat ('\n','Inferior day 14 vs day 0')
model <- aov(i_0_14 ~ Drug_group)
TukeyHSD(model)
confint(model, level=0.95)

cat ('\n','Temporal day 14 vs day 0')
model <- aov(t_0_14 ~ Drug_group)
TukeyHSD(model)
confint(model, level=0.95)

cat ('\n','Nasal day 14 vs day 0')
model <- aov(n_0_14 ~ Drug_group)
TukeyHSD(model)
confint(model, level=0.95)
```

```{r}
### b)

# no, different region have different react for treatment.

CORNEAL_DB$Meand0 <- rowMeans(CORNEAL_DB[, 3:7]) # mean value for day0
CORNEAL_DB$Meand7 <- rowMeans(CORNEAL_DB[, 8:12]) # mean value for day7
CORNEAL_DB$Meand14 <- rowMeans(CORNEAL_DB[, 13:17]) # mean value for day14
```


```{r}
### c)

cat ('day 7 vs day 0')
model <- aov((CORNEAL_DB$Meand0-CORNEAL_DB$Meand7) ~ Drug_group)
TukeyHSD(model)
confint(model, level=0.95)

cat ('\n')

cat ('\n','day 14 vs day 0')
model <- aov((CORNEAL_DB$Meand0-CORNEAL_DB$Meand14) ~ Drug_group)
TukeyHSD(model)
confint(model, level=0.95)

```

